<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Блог</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
<?php include __DIR__ . '/../parts/menu.phtml';?>

<h2>Посты</h2>

<?php foreach ($posts as $post): ?>
    <div>
        <a href="?page=post&id=<?= htmlspecialchars($post['id']) ?>"><b><?=htmlspecialchars($post['title']) ?></b></a>
    </div>
<?php endforeach; ?>

</body>
</html>
